# GitHub action to cross-compile LAMMPS-GUI for Windows using MinGW64 on Linux
name: "Cross-compile for Windows with MinGW64"

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{github.event_name == 'pull_request'}}

jobs:
  build:
    name: Cross-compile with MinGW64 and build NSIS installer
    if: ${{ github.repository == 'lammps/lammps-gui' }}
    runs-on: ubuntu-latest
    container:
      image: fedora:latest
    env:
      SIGN_DISABLE: 1

    steps:
    - name: Install system dependencies
      run: |
        dnf install -y \
            cmake \
            ninja-build \
            gcc-c++ \
            git \
            mingw32-nsis \
            mingw64-filesystem \
            mingw64-crt \
            mingw64-headers \
            mingw64-binutils \
            mingw64-gcc-c++ \
            mingw64-qt6-qtbase \
            mingw64-qt6-qtsvg \
            mingw64-pkg-config \
            mingw64-curl \
            mingw64-libgomp \
            mingw64-winpthreads \
            mingw64-fftw \
            mingw64-libjpeg-turbo \
            mingw64-libpng \
            doxygen \
            python3 \
            python3-pip \
            texlive-scheme-basic \
            texlive-collection-latexrecommended \
            texlive-collection-latexextra \
            texlive-collection-fontsrecommended \
            latexmk \
            wget \
            dos2unix \
            binutils \
            gzip

    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        fetch-depth: 20

    - name: Cross-compile LAMMPS-GUI via CMake
      shell: bash
      run: |
        mingw64-cmake -S . -B build \
              -D LAMMPS_GUI_USE_PLUGIN=yes \
              -D BUILD_DOC=yes \
              -D CODE_SIGNING=no
        cmake --build build --parallel 2

    - name: Build NSIS installer
      shell: bash
      run: |
        cmake --build build --target nsis
